# Generated by Django 2.2.12 on 2023-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('family', models.CharField(max_length=64)),
                ('students_code', models.CharField(max_length=6)),
            ],
        ),
    ]
